### ISSUE TITLE
Create config reference for manager settings

### ISSUE THREAD

**Issue by byDimasik** [Mirantis/mke-docs#110]
We've migrated some settings from the old MKE 3 TOML config to the new MKE 4 yaml config. The migrated settings are

```
EtcdStorageQuota
KubeAPIServerProfilingEnabled
KubeControllerManagerProfilingEnabled
KubeSchedulerProfilingEnabled
KubeSchedulerBindToAll
CipherSuitesForAPIServer
CipherSuitesForEtcdServer
KubeAPIServerAuditing
KubeAPIServerAuditLogMaxAge
KubeAPIServerAuditLogMaxBackup
KubeAPIServerAuditLogMaxSize
K8sEventRateLimit
KubeManagerTerminatedPodGCThreshold
K8sAlwaysPullImagesACEnabled
KubeAPIServerRequestTimeout
UnauthenticatedHTTP2DOSMitigation
```

Their descriptions can be found in MKE 3 docs - https://docs.mirantis.com/mke/3.7/ops/administer-cluster/configure-an-mke-cluster/configuration-options.html

MKE 3 docs are missing some of these settings, so, please feel free to reach out to me if you need help writing descriptions.

In the MKE 4 config file, the migrated settings look like this

```
spec:
  apiServer:
    profilingEnabled: false
    tlsCipherSuites: []
    audit:
      enabled: false
      logPath: /var/lib/k0s/audit.log
      maxAge: 30
      maxBackup: 10
      maxSize: 10
    eventRateLimit:
      enabled: false
      limits:
      - limit: ""
        limitQPS: 0
        limitBurst: 0
        limitCacheSize: 0
    requestTimeout: 1m0s
    alwaysPullImages: false
    unauthenticatedHTTP2DOSMitigation: false
  etcd:
    storageQuota: ""
    tlsCipherSuites: []
  controllerManager:
    profilingEnabled: false
    terminatedPodGCThreshold: 12500
  scheduler:
    profilingEnabled: false
    bindToAll: false
```

Here is 1-1 mapping

| MKE 3 TOML name                       | MKE 4 .spec                                       |
|---------------------------------------|---------------------------------------------------|
| EtcdStorageQuota                      | .spec.etcd.storageQuota                           |
| CipherSuitesForEtcdServer             | .spec.etcd.tlsCipherSuites                        |
| KubeAPIServerProfilingEnabled         | .spec.apiServer.profilingEnabled                  |
| CipherSuitesForAPIServer              | .spec.apiServer.tlsCipherSuites                   |
| KubeAPIServerAuditing                 | .spec.apiServer.audit.enabled                     |
| KubeAPIServerAuditLogMaxAge           | .spec.apiServer.audit.maxAge                      |
| KubeAPIServerAuditLogMaxBackup        | .spec.apiServer.audit.maxBackup                   |
| KubeAPIServerAuditLogMaxSize          | .spec.apiServer.audit.maxSize                     |
| K8sEventRateLimit                     | .spec.apiServer.eventRateLimit                    |
| K8sAlwaysPullImagesACEnabled          | .spec.apiServer.alwaysPullImages                  |
| KubeAPIServerRequestTimeout           | .spec.apiServer.requestTimeout                    |
| UnauthenticatedHTTP2DOSMitigation     | .spec.apiServer.unauthenticatedHTTP2DOSMitigation |
| KubeSchedulerBindToAll                | .spec.scheduler.bindToAll                         |
| KubeSchedulerProfilingEnabled         | .spec.scheduler.profilingEnabled                  |
| KubeControllerManagerProfilingEnabled | .spec.controllerManager.profilingEnabled          |
| KubeManagerTerminatedPodGCThreshold   | .spec.controllerManager.terminatedPodGCThreshold  |
