### ISSUE TITLE
Document the ability to add services

### ISSUE THREAD

**Issue by nwneisen** [Mirantis/mke-docs#146]
The MKE4 config allows for users to add components outside of what is provided as part of MKE4. This is done by using the `services` section in the config. 

This `services` section will basically pass the values through to k0rdent and follows the same format as a k0rdent services:
https://docs.k0rdent.io/v0.2.0/user/services/

In the MKE4 config, this is simplified to the following:

```
  services:
     - template: project-ingress-nginx-4.11.0
        name: ingress-nginx
        namespace: ingress
```
