### ISSUE TITLE
Update example for MKE 4 Kubelet Custom Profile

### ISSUE THREAD

**Issue by moshiurH** [Mirantis/mke-docs#175]
The hosts section looks more like this nowadays:
```
  hosts:
    - role: controller+worker
      ssh:
        address: 52.37.200.22
        keyPath: /home/moshiur/Documents/Github/mke/deployments/mke3/ssh_keys/mke3.pem
        port: 22
        user: ubuntu
    - role: worker
      ssh:
        address: 18.236.186.188
        keyPath: /home/moshiur/Documents/Github/mke/deployments/mke3/ssh_keys/mke3.pem
        port: 22
        user: ubuntu
        installFlags:
          - --profile=hardworker
```

The example from https://mirantis.github.io/mke-docs/docs/configuration/kubernetes/kubelet/#apply-a-custom-profile-to-a-node looks outdated:
```
  hosts:
  - role: single
    ssh:
      address: localhost
      keyPath: ~/.ssh/id_rsa
      port: 22
      user: root
      installFlags:
        - --profile=hardworker
```
