### ISSUE TITLE
Add a new section in metallb configuration

### ISSUE THREAD

**Issue by sakshisharma84** [Mirantis/mke-docs#209]
Add a new section for "Requesting specific IPs" right before https://github.com/Mirantis/mke-docs/blob/main/content/docs/configuration/metallb/_index.md#uninstall-metallb.

Raw content:

```
MetalLB allows you to request assignment from a specific address pool if you have a preference for a type of address but don’t require an exact one. To do this, add the metallb.universe.tf/address-pool annotation to your service, setting the annotation value to the name of the desired address pool. For example:

apiVersion: v1
kind: Service
metadata:
  name: nginx
  annotations:
    metallb.universe.tf/address-pool: production-public-ips
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: nginx
  type: LoadBalancer

For more details, please refer to https://metallb.universe.tf/usage/index.html#requesting-specific-ips
```
