### ISSUE TITLE
[BOP-1046] Telemetry config includes an optional clusterLabel field

### ISSUE THREAD

**Issue by RaunakShah** [Mirantis/mke-docs#277]
Similar to https://docs.mirantis.com/mke/3.7/ops/administer-cluster/configure-an-mke-cluster/configuration-options.html?highlight=cluster_label#tracking-configuration-table-optional we are including an optional field to send a cluster label with the telemetry data. 

Under https://mirantis.github.io/mke-docs/docs/configuration/telemetry, we need to add a new field under `spec.tracking`:

```
spec:
  tracking:
    enabled: true
    clusterLabel: "optional-label"
```

If this field was set in the MKE3 cluster, it will be automatically migrated to the MKE4 cluster after an upgrade.
