### ISSUE TITLE
LDAPS unsupported when using custom CAs

### ISSUE THREAD

**Issue by mzervakis** [Mirantis/mke-docs#307]
Setting the mkeconfig.spec.authentication.ldap.rootCA to the path of the custom CA will not configure the authentication correctly and LDAPS/636 will fail with tls verification error. The logic to create a secret for the customCA and mount it as volume in the authentication POD seems to be missing.

To support LDAPS rootCAData could be used instead of rootCA.

A workaround is to patch the authentication addon after installation.

```
CADATA=$(cat ca.crt | base64 -w0)
kubectl -n blueprint-system patch addons.blueprint.mirantis.com authentication --type merge --patch-file=/dev/stdin <<-EOF
apiVersion: blueprint.mirantis.com/v1alpha1
kind: Addon
metadata:
  name: authentication
  namespace: blueprint-system
spec:
  chart:
    values:
      config:
        connectors:
        - config:
            rootCAData: $CADATA
EOF
```
