### ISSUE TITLE
Missing yaml from GPU vectoradd

### ISSUE THREAD

**Issue by nwneisen** [Mirantis/mke-docs#326]
Some of the information was missed in the section to run vectoradd on a GPU workload: https://github.com/Mirantis/mke-docs/issues/302

We need to either include more information from https://docs.nvidia.com/datacenter/cloud-native/gpu-operator/latest/getting-started.html#cuda-vectoradd in our docs or else link to these NVIDIA docs. The current setup is missing the vectoradd apply and setup thus making the section unusable.

This section should include:

Create the workload
```
cat <<EOF | kubectl apply -f -
apiVersion: v1
kind: Pod
metadata:
  name: cuda-vectoradd
spec:
  restartPolicy: OnFailure
  containers:
  - name: cuda-vectoradd
    image: "nvcr.io/nvidia/k8s/cuda-sample:vectoradd-cuda11.7.1-ubuntu20.04"
    resources:
      limits:
        nvidia.com/gpu: 1
EOF
```

View the logs (our current section)
```
kubectl logs pod/cuda-vectoradd
```

Cleanup the pod
```
kubectl delete -f cuda-vectoradd.yaml
```
