### ISSUE TITLE
Drift detection and correction configuration docs

### ISSUE THREAD

**Issue by Algeran** [Mirantis/mke-docs#352]
# Description

## Configuration drift

Configuration drift is an issue when unexpected change takes place in an environment. It makes systems to become inconsistent and unpredictable. For example, it can be manual change or unexpected change by other systems in deployed services and configurations. In MKE clusters drift detection is enabled by default for all system services and services specified in MKE configuration. When any change is detected in watched resources (labels, annotations, spec or rules sections), the service state will be automatically re-synced back to its original state which is described in the MKE configuration.

## Disabling drift detection

> !!! Disabling drift detection and making changes to services may cause MKE cluster to become unstable. Be careful and only use this feature for testing purposes or if you know what you are doing.

It's not possible to disable the drift detection completely but you can specify some resources or kinds to be ignored or resource fields to be excluded from drift detection process.

### Ignore resources

You can stop certain resources from being tracked for configuration drift. This is done by adding the drift ignore patch selectors to MKE configuration. For instance, the following configuration will disable drift detection for `ingress-nginx-controller` deployment object in `ingress-nginx` namespace. This means any changes made to resources deployed by the MKE itself will be flagged as a configuration drift. However, any modifications directly to the `ingress-nginx-controller` deployment won't be detected as drift.
```
spec:
  driftDetection:
    driftIgnore:
      - group: apps
        version: v1
        kind: Deployment
        name: ingress-nginx-controller
        namespace: ingress-nginx
```

Patch selector can have following properties:
- `group` - API group to select resources from
- `version` - version of the API group to select resources from
- `kind` - kind of the API group to select resources from
- `name` - name to match resources with
- `namespace` - namespace to select resources from
- `annotationSelector` - a string that follows the [label selection expression](https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/#api). It matches with resource annotations
- `labelSelector` - a string that follows the [label selection expression](https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/#api). It matches with resource labels

All fields are optional and it's allowed to specify any or all of them to filter resources that must be ignored for drift detection.

> !!! It's not possible to filter resources by service with patch selector. This means if you decide to disable drift detection for specific resources, make sure that it will filter only required cluster resources.

### Ignore fields

It's also possible to optionally specify only certain fields to be excluded from drift detection using JSON Pointers.

Here's an example of MKE configuration:
```
spec:
  driftDetection:
    driftExclusions:
      - paths:
           - "/spec/replicas"
        target:
          group: apps
          version: v1
          kind: Deployment
          name: ingress-nginx-controller
          namespace: ingress-nginx
```
